set background=dark
set title
set number
set nowrap
set hlsearch
set incsearch
set ignorecase
set smartcase
set autoindent
set copyindent
set smarttab
set shiftround
set tabstop=4
set shiftwidth=4
set backspace=indent,eol,start
